name: bmicalc
description: Simple BmiCalculator

version: 1.0.0+1

environment:
  sdk: ">=2.12.0 < 3.0.0"
  flutter:

dependencies:
  cupertino_icons: ^1.0.2
  flutter:
    sdk: flutter
  #UI
  flutter_icons:
  #S\e
  provider: ^5.0.0-nullsafety.5
  #common
  intl: ^0.17.0
  hive: ^1.6.0-nullsafety.2
  hive_flutter: ^1.0.0-nullsafety.0
  flutter_staggered_animations:
    git:
      url: https://github.com/mobiten/flutter_staggered_animations.git
      ref: develop
  #ads

dev_dependencies:
  build_runner:
  flutter_driver:
    sdk: flutter
  flutter_test:
    sdk: flutter
  hive_generator: 0.9.0-nullsafety.1
  test: ^1.16.5

flutter:
  uses-material-design: true
