name: BmiCalc
description: Simple BmiCalculator

version: 1.0.0+1

environment:
  sdk:
  flutter:
  
dependencies:
  flutter:
    sdk: flutter
  #UI
  flutter_icons:
  cupertino_icons:
  #S\e
  provider:
  #common
  intl:
  hive:
  hive_flutter:
    git:
      url: git://github.com/Mravuri96/hive.git #Enables macos Support
      path: hive_flutter
  flutter_staggered_animations:
  #ads

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_driver:
    sdk: flutter
  test:
  build_runner:
  hive_generator:

dependency_overrides:
  dartx:
  path:

flutter:
  uses-material-design: true
